### ISSUE TITLE
milestone v1.5 acrescentada 

### ISSUE THREAD

**Issue by arthurdelmas** [arthurdelmas/ex17#10]
Pessoal, criei a milestone v1.1 para o mesmo dia da v1.0 com o objetivo de termos o código 100% concluído e com a apresentação em PDF. #3

**Comment by bapc** [comment]
Ok

**Comment by bapc** [comment]
Poderíamos criar uma apresentação compartilhada do Google para montar a apresentação.

**Comment by arthurdelmas** [comment]
Boa ideia, vamos adiantar o código para começar

**Comment by Messias-Lima** [comment]
Release feito.
