### ISSUE TITLE
Função para trabalhar com a arvore 

### ISSUE THREAD

**Issue by bapc** [arthurdelmas/ex17#11]
Precisamos de uma função para trabalhar com arvore na pós ordem. Alguém pode ajudar?

**Comment by arthurdelmas** [comment]
Vamos lá! Qual tua ideia para a gente trabalhar?

**Comment by bapc** [comment]
Fazermos condições com if e else, com dados obtidos da arvore.

**Comment by arthurdelmas** [comment]
Acrescentei também para os caso do operador binário e operador para ER minima.
Se tiver tudo ok, me confirma e já fecha esse issue.

**Comment by bapc** [comment]
Comentasse tudo?

**Comment by arthurdelmas** [comment]
Acredito que ta tudo ok.

**Comment by bapc** [comment]
Certo então.
