### ISSUE TITLE
Função Quebra expressão

### ISSUE THREAD

**Issue by DaviPSS** [arthurdelmas/ex17#8]
Ele é responsável em quebra a expressão regular em pequenas partes e armazena em árvore binária.

**Comment by DaviPSS** [comment]
Alguém me ajuda a completar essa parte? 4e734b7ad1cc2fd5860cf09d25e83e3a134b4ccf

**Comment by bapc** [comment]
Eu vou ver o código e te ajudo.

**Comment by DaviPSS** [comment]
Okey! @bapc

**Comment by DaviPSS** [comment]
Feita a função.
