### ISSUE TITLE
Help na função que separa as ER

### ISSUE THREAD

**Issue by arthurdelmas** [arthurdelmas/ex17#9]
Pessoal, estou precisando remover parenteses das funções regulares, quando elas estiverem contidas nelas mesmas, alguém pode me ajudar? 
Deixei um parte comentada para encaixar isso.

**Comment by DaviPSS** [comment]
Verifiquei na tua função e posso fazer sim.

**Comment by arthurdelmas** [comment]
Valeu, @DaviPSS , após adicionar isso, faz a chamada dela na _".h"_

**Comment by arthurdelmas** [comment]
Função concluída!
Obrigado, @DaviPSS
